extern alias Core;
using System;
using Core.DwC_A;

namespace DwC_A.Mapping
{
    /// <summary>
    /// Factory for creating mappers to map IRow to an instance of an class of type T
    /// </summary>
    public static class MapperFactory
    {
        /// <summary>
        /// Creates a mapper
        /// </summary>
        /// <seealso cref="Attributes.TermAttribute"/>
        /// <typeparam name="T">Type to map to</typeparam>
        /// <param name="mapFunc">When type T is annotated with <typeparamref name="TermAttribute"/> then use the Map method that is generated by the source generator.
        /// Otherwise define a method to map IRow fields to properties of type T.
        /// </param>
        /// <returns>A new mapper</returns>
        public static IMapper<T> CreateMapper<T>(Action<T, IRow> mapFunc) where T : new()
        {
            return new Mapper<T>(mapFunc);
        }
    }
}
