name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: DwC-A_dotnet.Mapping.nupkg
        path: src/DwC-A_dotnet.Mapping/bin/Release/DwC-A_dotnet.Mapping.*.nupkg  
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        name: dwca-codegen.nupkg
        path: src/dwca-codegen/bin/Release/dwca-codegen.*.nupkg  
    - name: Test
      run: dotnet test --verbosity normal -p:CollectCoverage=true
