# This is a basic workflow to help you get started with Actions
name: PublishNuget (dwca-codegen)

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: 8.0.x
           
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build
        run: dotnet build -c Release src/dwca-codegen/dwca-codegen.csproj
      - name: Package
        run: dotnet pack -c Release -o . src/dwca-codegen/dwca-codegen.csproj
      - name: Publish
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json

